# Generated by Django 5.2.5 on 2025-08-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribution',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attribution',
            constraint=models.UniqueConstraint(fields=('etudiant_id',), name='unique_advisor_per_student'),
        ),
    ]
