# Generated by Django 5.2.5 on 2025-09-05 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0002_alter_attribution_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True),
        ),
    ]
